"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 3.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
from decouple import config
from datetime import timedelta
import os, logging.config


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# Guard against short key at startup
if len(SECRET_KEY.encode()) < 32:
    raise ValueError("SECRET_KEY must be at least 32 bytes long")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', cast=bool, default=True)

ALLOWED_HOSTS = ['127.0.0.1', '.vercel.app']

# CORS_ALLOWED_ORIGINS = ["http://localhost:5173", "http://127.0.0.1:5173", "https://dwellingbloom.netlify.app"]

CSRF_TRUSTED_ORIGINS = ['http://*', 'https://*', 'https://dwellingbloom.netlify.app']

CORS_ALLOW_ALL_ORIGINS = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # 3rd-party libraries
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',
    'drf_spectacular',
    'corsheaders',

    # Local apps
    'authentication',
    # 'properties',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        # # Test with SQLite for simplicity, switch to MySQL for production
        # 'ENGINE': 'django.db.backends.sqlite3',
        # 'NAME': BASE_DIR / 'db.sqlite3',

        # PostgreSQL configuration for production
        'ENGINE': 'django.db.backends.postgresql',
        'HOST': config('DB_HOST'),
        'PORT': config('DB_PORT'),
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASS'),

        # # Add to above for MySQL configuration
        # 'OPTIONS': {
        #     'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        # },
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


''' Custom django settings '''
# Auth config
AUTH_USER_MODEL = 'authentication.UserModel'
ACCOUNT_LOGIN_METHODS = {'email'}  # Use email for authentication
ACCOUNT_EMAIL_REQUIRED = True  # Email is required
ACCOUNT_UNIQUE_EMAIL = True  # Email must be unique
ACCOUNT_USERNAME_REQUIRED = False  # No username is required
ACCOUNT_USER_MODEL_USERNAME_FIELD = None  # No username field in the user model

SITE_ID = 1


# static files config
STATIC_ROOT = BASE_DIR/'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


# DRF-Spectacular config
SPECTACULAR_SETTINGS = {
    'TITLE': 'Dwelling Bloom API',
    'DESCRIPTION': 'Dwelling Bloom is a real estate platform designed to simplify the process of renting or buying properties in Nigeria eliminating the fraudulent agent and uneccessary fees. This API provides the backend infrastructure necessary for user authentication, property management, interaction with a database of available properties, and payment.',
    'VERSION': '1.0.0',
    'CONTACT': {'name': 'Peter Oyelegbin', 'url': 'https://peteroyelegbin.com.ng', 'email': 'peteroyelegbin@gmail.com'},
    'LICENSE': {'name': 'MIT License', 'url': 'https://opensource.org/licenses/MIT'},
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENTS': {
        'securitySchemes': {
            'Bearer': {
                'type': 'http',
                'scheme': 'bearer',
                'bearerFormat': 'JWT',
            }
        }
    },
    'SECURITY': [{'Bearer': []}],
    'TAGS': [
        {'name': 'Auth',  'description': 'Authentication endpoints'},
        {'name': 'Users', 'description': 'User profile endpoints'},
        {'name': 'Admin', 'description': 'Admin management endpoints'},
    ],
}


# Rest framework config
REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_AUTHENTICATION_CLASSES': [
        # 'rest_framework_simplejwt.authentication.JWTAuthentication',
        'utils.jwt_config.CustomJWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '5/minute',
        'user': '100/minute',
    },
}


# JWT config
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=int(config('ACCESS_TOKEN_EXPIRE_MINUTES'))),  # Shorter for security

    'REFRESH_TOKEN_LIFETIME': timedelta(days=int(config('REFRESH_TOKEN_EXPIRE_DAYS'))),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,                # Prevent token reuse
    'UPDATE_LAST_LOGIN': True,

    # Algorithm for signing tokens
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': config('SECRET_KEY'),
    'VERIFYING_KEY': None,                           # Explicitly set

    # Token type header & User ID claim
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',

    # Token identification
    'JTI_CLAIM': 'jti',                              # This is crucial for blacklisting

    # Token class
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),

    # Token type claim
    'TOKEN_TYPE_CLAIM': 'token_type',
}


# Cache config
CACHES = {
    # 'default': {
    #     'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
    #     'LOCATION': 'unique-snowflake',
    # }

    # Add Redis configuration for production
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': config("REDIS_URL"),
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        }
    }
}

# Use Redis as session backend (optional but recommended)
SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_CACHE_ALIAS = "default"


# Celery Config
CELERY_TIMEZONE = "Nigeria/Lagos"
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 minutes
CELERY_BROKER_URL = config("REDIS_URL")
CELERY_RESULT_BACKEND = config("REDIS_URL")
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'


FRONTEND_URL = "http://127.0.0.1:8000/api/v1/auth"


# Email config
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = config("EMAIL_HOST")
EMAIL_PORT = config("EMAIL_PORT")
DEFAULT_FROM_EMAIL = config("EMAIL_HOST_USER")
EMAIL_HOST_USER = config("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = config("EMAIL_HOST_PASSWORD")
EMAIL_USE_TLS = config("EMAIL_USE_TLS", cast=bool, default=False)
EMAIL_USE_SSL = config("EMAIL_USE_SSL", cast=bool, default=False)
EMAIL_TIMEOUT = 30  # 30 sec


# Logging config
IS_VERCEL = os.environ.get("VERCEL") is not None

if IS_VERCEL:
    general_handler = {
        "level": "INFO",
        "class": "logging.StreamHandler",
        "formatter": "verbose",
    }
    email_handler = {
        "level": "ERROR",
        "class": "logging.StreamHandler",
        "formatter": "verbose",
    }
else:
    general_handler = {
        "level": "INFO",
        "class": "logging.FileHandler",
        "filename": "general.log",
        "formatter": "verbose",
    }
    email_handler = {
        "level": "ERROR",
        "class": "logging.FileHandler",
        "filename": "email_errors.log",
        "formatter": "verbose",
    }

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {asctime} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file_general': general_handler,
        'file_email': email_handler,
    },
    'loggers': {
        'django': {
            'handlers': ['file_general'],
            'level': 'ERROR',
            'propagate': True,
        },
        'general_logger': {
            'handlers': ['file_general'],
            'level': 'INFO',
            'propagate': False,
        },
        'email_logger': {
            'handlers': ['file_email'],
            'level': 'ERROR',
            'propagate': False,
        },
    },
}

logging.config.dictConfig(LOGGING)
