# Generated by Django 4.2.18 on 2026-06-02 14:58

import cloudinary_storage.storage
import cloudinary_storage.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import properties.models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Apartment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "apartment_type",
                    models.CharField(
                        choices=[
                            ("STUDIO", "Studio"),
                            ("ONE_BED", "1 Bedroom"),
                            ("TWO_BED", "2 Bedroom"),
                            ("THREE_BED", "3 Bedroom"),
                            ("DUPLEX", "Duplex"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("bedrooms", models.PositiveIntegerField()),
                ("bathrooms", models.PositiveIntegerField()),
                ("street", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                (
                    "video",
                    models.FileField(
                        storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(),
                        upload_to="videos/",
                        validators=[
                            cloudinary_storage.validators.validate_video,
                            properties.models.validate_video_size,
                        ],
                    ),
                ),
                ("monthly_rent", models.DecimalField(decimal_places=2, max_digits=10)),
                ("agreement_fee", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("C_OF_O", "Certificate of Origin"),
                            ("REFERENCE_LETTER", "Reference Letter"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "document_file",
                    models.FileField(
                        storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(),
                        upload_to="documents/",
                        validators=[properties.models.validate_file_size],
                    ),
                ),
                ("is_available", models.BooleanField(default=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_apartments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ApartmentImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="images/",
                        validators=[properties.models.validate_file_size],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "apartment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="properties.apartment",
                    ),
                ),
            ],
        ),
    ]
