# Generated by Django 4.2.18 on 2026-06-05 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='apartment_type',
            field=models.CharField(choices=[('STUDIO', 'Studio'), ('ONE_BED', '1 Bedroom'), ('TWO_BED', '2 Bedroom'), ('THREE_BED', '3 Bedroom'), ('DUPLEX', 'Duplex')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='city',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='is_available',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='is_verified',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='state',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
