# Generated by Django 4.2.18 on 2026-09-19 17:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "properties",
            "0002_alter_apartment_apartment_type_alter_apartment_city_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="apartment",
            old_name="owner",
            new_name="landlord",
        ),
        migrations.AlterField(
            model_name="apartment",
            name="agreement_fee",
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name="apartment",
            name="monthly_rent",
            field=models.PositiveBigIntegerField(),
        ),
    ]
