# Generated by Django 4.2.18 on 2026-06-05 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='role',
            field=models.CharField(choices=[('TENANT', 'Tenant'), ('OWNER', 'Owner')], db_index=True, default='TENANT', max_length=10),
        ),
    ]
