# Generated by Django 4.2.18 on 2026-08-04 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_usermodel_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresettoken',
            name='failed_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
