# Generated by Django 4.2.18 on 2026-09-19 17:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0003_add_failed_attempts_to_passwordresettoken"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usermodel",
            name="account_name",
        ),
        migrations.RemoveField(
            model_name="usermodel",
            name="account_number",
        ),
        migrations.RemoveField(
            model_name="usermodel",
            name="bank_name",
        ),
        migrations.AlterField(
            model_name="usermodel",
            name="role",
            field=models.CharField(
                choices=[("TENANT", "Tenant"), ("LANDLORD", "Landlord")],
                db_index=True,
                default="TENANT",
                max_length=10,
            ),
        ),
    ]
