name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Test Application
    runs-on: ubuntu-latest

    steps:
      - name: Display Trigger Information
        run: |
          echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
          echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
          echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."

      - name: Checkout Repository Code
        uses: actions/checkout@v3

      - name: Confirm Repository Cloning
        run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."

      - name: Set Up Python Environment
        run: echo "🖥️ Setting up Python environment for testing."

      - name: Install Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          echo "📦 Installing project dependencies."
          pip install -r requirements.txt

      - name: Execute Test Suite
        run: |
          echo "🖥️ Running tests."
          python manage.py test
          